- hosts: 192.168.43.109
vars:
  - port: "8012"
tasks:
  - name: Add EPEl repo
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
- name: Installing httpd webserver
    package:
      name: "httpd"
      state: present
- name: Copying conf file
    template:
      dest: "/etc/httpd/conf.d/myhttpd.conf"
      src: "myhttpd.conf"
    notify:
      - changed
- name: Adding rule for http
    firewalld:
      port: "{{ port }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes
- name: Staring httpd service
    service:
      name: httpd
      state: started
handlers:
  - name: changed
    service:
      name: "httpd"
      state: restarted
      enabled: yes
