- hosts: 192.168.43.109
  vars:
  - port_no: "8012"
  - dir: "/var/www/web"

  tasks:
  - name: Add EPEl repo
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"

  - name: Installing httpd webserver
    package:
      name: "httpd"
      state: present

  - name: Creating directory
    file: 
      path: "{{ dir }}"
      state: directory
 
  - name: Copy webserver content
    copy:
      src: index.html
      dest: "{{ dir }}/index.html"

  - name: Checking Webserver Configuration file
    template:
      dest: "/etc/httpd/conf.d/port-dr.conf"
      src: "port-dr.conf.j2"

    notify:
    - config-changed

  - name: Adding rule for http
    firewalld:
      port: "{{ port_no }}/tcp"
      state: enabled
      permanent: yes
      immediate: yes


  - name: starting webserver service 
    service:
     name: "httpd"
     state: started

    
  handlers:
  - name: config-changed
    service:
      name: "httpd"
      state: restarted
      enabled: yes



